### ISSUE TITLE
Windows binary depends on seemingly unneeded debug libraries

### ISSUE THREAD

**Issue by pogmommy** [jclehner/patchchk#1]
Trying to launch the windows executable yields two errors:

`The code execution cannot proceed because ucrtbased.dll was not found. Reinstalling the program may fix this problem.`

`The code execution cannot proceed because VCRUNTIME140D.dll was not found. Reinstalling the program may fix this problem.`

These libraries are not supposed to be redistributed and are only available through certain components of Visual Studio. I found them in these specific components listed below, but other versions of these components will probably(?) work as well.

`MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)` - provides VCRUNTIME140D.dll
`Windows 11 SDK (10.0.22621.0)` OR the [standalone Windows SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/)- provides ucrtbased.dll

With these installed, the program runs without issue and without recompilation.

I was able to successfully compile the windows binary for release, which removes the dependencies on these two libraries. It can be done by adding `-DCMAKE_BUILD_TYPE=Release` to line 6 of [build-release-msvc.bat](https://github.com/jclehner/patchchk/blob/master/build-release-msvc.bat) so that it reads `cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..`

I'm not particularly experienced with C or Windows development, so I'm sure there's a better/more intuitive way of including this change which is why this isn't a PR. I'm also unsure if there is a specific reason for publishing the debug build, but in my testing (on a machine without visual studio or any of its components installed), a release build works as expected, and saves users the several GB of Visual Studio components they might not otherwise need.

**Comment by jclehner** [comment]
Thanks, I've updated the build scripts accordingly, and released [version 3](https://github.com/jclehner/patchchk/releases/tag/v3)!
